import React from 'react'
import Head from 'next/head'
import { GetStaticProps } from 'next'

import { format, parseISO } from 'date-fns'
import ptBR from 'date-fns/locale/pt-BR'

import { api } from '../services/api'
import { formatedDurationTimeEpisode } from '../utils/formatedDurationTimeEpisode'

import { Container, Content } from '../styles/pages/index'
import CardEpisodePodcast from '../components/CardEpisodePodcast'
import TableEpisodesPodcast from '../components/TableEpisodesPodcast'

interface episode {
  id: string
  title: string
  members: string
  thumbnail: string
  description: string
  publishedAt: Date
  url: string
  type: string
  duration: number
}

interface episodeJSON {
  id: string
  title: string
  members: string
  thumbnail: string
  description: string
  published_at: string
  file: {
    url: string
    type: string
    duration: number
  }
}

interface HomeDataProps {
  episodes: Array<episode>
}

const Home: React.FC<HomeDataProps> = episodes => {
  return (
    <Container>
      <Head>
        <title>prisma.cast | O melhor para você ouvir, sempre!</title>

        <meta name="description" content="Generated by create next app" />
      </Head>

      <Content>
        <section className="latestReleases">
          <h2>Últimos lançamentos</h2>
          <div className="cardEpisode">
            <CardEpisodePodcast />
            <CardEpisodePodcast />
          </div>
        </section>
        <section className="allEpisodes">
          <h2>Todos os episódios</h2>
          <TableEpisodesPodcast />
        </section>
      </Content>
    </Container>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get('episodes', {
    params: {
      _limit: 12,
      _sort: 'published_at',
      _order: 'desc'
    }
  })

  const episodesFormated: episode = data.map(function (ep: episodeJSON) {
    return {
      id: ep.id,
      title: ep.title,
      members: ep.members,
      thumbnail: ep.thumbnail,
      description: ep.description,
      publishedAt: format(parseISO(ep.published_at), 'd MMM yy', {
        locale: ptBR
      }),
      url: ep.file.url,
      type: ep.file.type,
      duration: ep.file.duration,
      durationFormated: formatedDurationTimeEpisode(ep.file.duration)
    }
  })

  return {
    props: {
      episodes: episodesFormated
    }
  }
}
